version: 2.1

parameters:
  run_workflow_build:
    default: true
    type: boolean
  run_workflow_test:
    default: true
    type: boolean
  run_workflow_deploy:
    default: true
    type: boolean

jobs:
  job_a:
    docker:
      - image: cimg/base:stable # Specify a Docker image
    steps:
      - run: echo "hello"
  job_b:
    docker:
      - image: cimg/base:stable # Specify a Docker image for job_b
    steps:
      - run: echo "Executing job_b steps"
  job_c:
    docker:
      - image: cimg/base:stable # Specify a Docker image for job_c
    steps:
      - run: echo "Executing job_c steps"

workflows:
  version: 2
  conditional_workflow:
    jobs:
      - job_a:
          when: << pipeline.parameters.run_workflow_build >>
      - job_b:
          when: << pipeline.parameters.run_workflow_test >>
      - job_c:
          when: << pipeline.parameters.run_workflow_deploy >>