name: Pull Request

on: [workflow_dispatch]
jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: staging-and-pull-request
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: "staging-and-pull-request"
          target-slug: gh/ziedtabesto/test-todomvc-using-app-actions
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_CI_API_TOKEN }}